added spring boot icon
danielcranney/profileme-dev pull request #169
Opened 2024-07-21 05:19 UTC by its-me-ojas

# Description:
- This pull request adds the Spring Boot icon to the code as specified in the project’s icon addition instructions. The icon is included in the relevant sections to enhance the visual representation of the project’s technology stack.
# Changes:
- Added the Spring Boot icon in the designated sections of the project as outlined in the README.
# Related Issue:
- Addresses issue #168 .

2024-07-28 03:02 UTC, its-me-ojas commented
Hi @danielcranney ,

Could you please review my recent pull request?

Thanks

2024-09-01 23:49 UTC, LachyTech commented on styles/globals.css
> +  springboot {
This needs to be `.springboot` to work correctly as a CSS class.

2024-09-01 23:49 UTC, LachyTech commented on styles/globals.css
> +    @apply bg-[url('https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/skills/springboot-colored.svg')] dark:bg-[url('https://raw.githubusercontent.com/danielcranney/r
You don't need the dark:bg attribute if there is only one coloured icon.

2024-09-01 23:53 UTC, LachyTech requested changes
After a few minor changes this PR would be good to go. I like the icons. :)

2024-09-01 23:53 UTC, LachyTech commented on package-lock.json
Please only include changes that are relevant to the change being submitted.

2025-01-02 19:57 UTC, its-me-ojas commented
@LachyTech I've implemented the suggested changes. Please review the updates and let me know if there's anything else to address. Thanks!

2025-06-18 18:05 UTC, danielcranney approved these changes
Great work @its-me-ojas  and thanks @LachyTech  for reviewing the code along the way.

2025-06-18 18:06 UTC, merged